global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'kafka-localstack-monitor'

rule_files:
  # - "kafka_rules.yml"

scrape_configs:
  # Kafka metrics via kafka-exporter
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka-exporter:9308']
    scrape_interval: 15s
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: kafka-exporter:9308

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 15s

  # Kafka Connect metrics (if JMX is enabled)
  - job_name: 'kafka-connect'
    static_configs:
      - targets: ['kafka-connect:8083']
    scrape_interval: 30s
    metrics_path: /metrics
    scrape_timeout: 10s

  # Schema Registry metrics (if available)
  - job_name: 'schema-registry'
    static_configs:
      - targets: ['schema-registry:8081']
    scrape_interval: 30s
    metrics_path: /metrics
    scrape_timeout: 10s

  # Additional monitoring targets (uncomment as needed)
  # - job_name: 'node-exporter'
  #   static_configs:
  #     - targets: ['node-exporter:9100']
  #   scrape_interval: 15s

  # - job_name: 'cadvisor'
  #   static_configs:
  #     - targets: ['cadvisor:8080']
  #   scrape_interval: 15s

# Alerting configuration (optional)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#             - alertmanager:9093

# Storage configuration 
storage:
  tsdb:
    # retention.time: 7d
    # retention.size: 1GB