@StressTestsWebApi_HostAddress = http://localhost:5294


# NO OCC
POST {{StressTestsWebApi_HostAddress}}/Stress/
Accept: application/json
Content-Type: application/json

{
  "writeCycleCount": 30000,
  "streamsCount": 1,
  "degreeOfParallelismPerStream": 1,
  "batchSize": 10,
  "streamPrefix": "no-conflicts"
}
###

# OCC
POST {{StressTestsWebApi_HostAddress}}/Stress/
Accept: application/json
Content-Type: application/json

{
  "writeCycleCount": 30000,
  "streamsCount": 1,
  "degreeOfParallelismPerStream": 20,
  "batchSize": 10,
  "streamPrefix": "with-conflicts"
}
###
