{
 "title": "EvDB",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Events Stored Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg  (rate(evdb_events_stored_duration_milliseconds_sum[$__rate_interval]) / rate(evdb_events_stored_duration_milliseconds_count[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Events Stored Count ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum(rate(evdb_events_stored_total[$__rate_interval])) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Snapshots Stored Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg  (rate(evdb_snapshot_stored_duration_milliseconds_sum[$__rate_interval]) / rate(evdb_snapshot_stored_duration_milliseconds_count[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Events Stored Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by(evdb_domain, evdb_partition) (rate(evdb_events_stored_duration_milliseconds_sum[$__rate_interval]) / rate(evdb_events_stored_duration_milliseconds_count[$__rate_interval]))",
     "legendFormat": "{{evdb_domain}}:{{evdb_partition}}"
    }
   ]
  },
  {
   "title": "Events Stored Count ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum (rate(evdb_events_stored_duration_milliseconds_count[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Snapshots Stored Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by(evdb_domain, evdb_partition, evdb_view_name) (rate(evdb_snapshot_stored_duration_milliseconds_sum[$__rate_interval]) / rate(evdb_snapshot_stored_duration_milliseconds_count[$__rate_interval]))",
     "legendFormat": "{{evdb_domain}}:{{evdb_partition}}→{{evdb_view_name}}"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Events Stored Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by(evdb_domain, evdb_partition, evdb_stream_id) (rate(evdb_events_stored_duration_milliseconds_sum[$__rate_interval]) / rate(evdb_events_stored_duration_milliseconds_count[$__rate_interval]))",
     "legendFormat": "{{evdb_domain}}:{{evdb_partition}}:{{evdb_stream_id}}"
    }
   ]
  },
  {
   "title": "Snapshots Stored Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by(evdb_domain, evdb_partition, evdb_stream_id,evdb_view_name) (rate(evdb_snapshot_stored_duration_milliseconds_sum[$__rate_interval]) / rate(evdb_snapshot_stored_duration_milliseconds_count[$__rate_interval]))",
     "legendFormat": "{{evdb_domain}}:{{evdb_partition}}:{{evdb_stream_id}}→{{evdb_view_name}}"
    }
   ]
  },
  {
   "title": "Events Stored Count (Stacked)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(evdb_domain, evdb_partition, evdb_stream_id) (rate(evdb_events_stored_duration_milliseconds_count[$__rate_interval]))",
     "legendFormat": "{{evdb_domain}}:{{evdb_partition}}:{{evdb_stream_id}}"
    }
   ]
  },
  {
   "title": "Snapshots Stored Count (Stacked)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(evdb_domain, evdb_partition, evdb_stream_id,evdb_view_name) ( rate(evdb_snapshot_stored_duration_milliseconds_count[$__rate_interval]))",
     "legendFormat": "{{evdb_domain}}:{{evdb_partition}}:{{evdb_stream_id}}→{{evdb_view_name}}"
    }
   ]
  },
  {
   "title": "Get From Storage Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by(evdb_domain, evdb_partition) (rate(evdb_factory_get_duration_milliseconds_sum[$__rate_interval]) / rate(evdb_factory_get_duration_milliseconds_count[$__rate_interval]))",
     "legendFormat": "{{evdb_domain}}:{{evdb_partition}}"
    }
   ]
  },
  {
   "title": "Get From Storage Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by(evdb_domain, evdb_partition,evdb_stream_id) (rate(evdb_factory_get_duration_milliseconds_sum[$__rate_interval]) / rate(evdb_factory_get_duration_milliseconds_count[$__rate_interval]))",
     "legendFormat": "{{evdb_domain}}:{{evdb_partition}}:{{evdb_stream_id}}"
    }
   ]
  }
 ]
}