global:
  scrape_interval: 5s
  scrape_timeout: 5s
  evaluation_interval: 5s
#  scrape_interval: 15s
#  scrape_timeout: 10s
#  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
    api_version: v1
scrape_configs:
- job_name: bang
  honor_timestamps: true
  # scrape_interval: 15s
  # scrape_timeout: 15s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - host.docker.internal:5028 # when prometheus is hosting within a docker container
    - localhost:5028            # when prometheus is hosting on localhost
# - job_name: the-job-name
#   honor_timestamps: true
#   scrape_interval: 15s
#   scrape_timeout: 10s
#   metrics_path: /metrics
#   scheme: http
#   static_configs:
#   - targets:
#     - localhost:9090
