# Sample

This sample is about students performance evaluation.

Student can belong to classes for a period.
During this period it can take a tests.

The Sample is looking to digest the Student activity's data in the following views:
- Student average grade (StudentAveregeScore)
- Student average per Course (StudentAveregeScorePerCourse)
- Top student at the last week (StudentInCourse)
- Top student in course at the last week (StudentInCourse)