title: Eventualize
description: A simple & powerful event sourcing framework
theme: just-the-docs
logo: images/eventualize-icon-with-text.png

url: https://eventualizedb.com

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.3"

aux_links:
  "Eventalize on GitHub":
    - "//github.com/outsidenote/eventualize"
aux_links_new_tab: false

# Heading anchor links appear on hover over h1-h6 tags in page content
# allowing users to deep link to a particular heading on a page.
#
# Supports true (default) or false
heading_anchors: true

color_scheme: dark