name: Increment Version (Directory.Build.props)

# doc:               https://docs.github.com/en/actions
# variables:         https://docs.github.com/en/actions/learn-github-actions/environment-variables
# secrets:           https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#example-17
# env:               https://docs.github.com/en/actions/learn-github-actions/environment-variables
# reusable workflow: https://docs.github.com/en/actions/learn-github-actions/reusing-workflows#access-to-reusable-workflows

on:
  push:
    branches: ["main"]

jobs:
  version_increment:
    # if: ${{ github.event.workflow_run.conclusion != 'failure' }}
    name: Increment Version
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{secrets.CI_PAT}}

      - name: Increment Major Version
        id: increment_major_version
        if: ${{ startsWith(github.event.head_commit.message, '[MAJOR]') }}
        run: |
          perl -pi -e 's#<Version>([0-9]+)\.([0-9]+)\.([0-9]+)(.*)</Version>#"<Version>${\( $1+1 )}.$2.$3$4</Version>"#eg' Directory.Build.props
          awk -vpre="prefix" -F '[<>]' '/Version/{print "version="$3; exit}' Directory.Build.props >> $GITHUB_OUTPUT
        shell: bash

      - name: Increment Minor Version
        id: increment_monir_version
        if: ${{ startsWith(github.event.head_commit.message, '[MINOR]') }}
        run: |
          perl -pi -e 's#<Version>([0-9]+)\.([0-9]+)\.([0-9]+)(.*)</Version>#"<Version>$1.${\( $2+1 )}.$3$4</Version>"#eg' Directory.Build.props
          awk -vpre="prefix" -F '[<>]' '/Version/{print "version="$3; exit}' Directory.Build.props >> $GITHUB_OUTPUT
        shell: bash

      - name: Increment Patch Version
        id: increment_patch_version
        if: ${{ ! startsWith(github.event.head_commit.message, '[MAJOR]') && ! startsWith(github.event.head_commit.message, '[MINOR]')}}
        run: |
          perl -pi -e 's#<Version>([0-9]+)\.([0-9]+)\.([0-9]+)(.*)</Version>#"<Version>$1.$2.${\( $3+1 )}$4</Version>"#eg' Directory.Build.props
          awk -vpre="prefix" -F '[<>]' '/Version/{print "version="$3; exit}' Directory.Build.props >> $GITHUB_OUTPUT
        shell: bash

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_user_name: CI/CD
          commit_user_email: ${{ inputs.author-email }}
          commit_message: "[skip ci] Increment Version"
          commit_options: "--no-verify"
          push_options: "--no-verify"
          tagging_message: "v${{join(steps.*.outputs.version)}}"
  
      - name: publish on version change
        id: publish_nuget
        run: |
          dotnet build -c Release Eventualize.Core/Eventualize.Core.csproj
          dotnet build -c Release Adapters/Store/Sql/Eventualize.Core.Adapters.SqlStore.Adapters/Eventualize.Core.Adapters.SqlStore.Adapters.csproj -o .
          dotnet build -c Release Adapters/Store/Eventualize.Core.Adapters.RelationalStore.Common/Eventualize.Core.Adapters.RelationalStore.Common.csproj -o .
          dotnet build -c Release Adapters/Store/Eventualize.Core.Adapters.RelationalStore.Adapters/Eventualize.Core.Adapters.RelationalStore.Adapters.csproj -o .
          dotnet pack  --no-build -c Release Eventualize.Core/Eventualize.Core.csproj -o .
          dotnet pack  --no-build -c Release Eventualize.Core.Abstractions/Eventualize.Core.Abstractions.csproj -o .
          dotnet pack  --no-build -c Release Adapters/Store/Sql/Eventualize.Core.Adapters.SqlStore.Adapters/Eventualize.Core.Adapters.SqlStore.Adapters.csproj -o .
          dotnet pack  --no-build -c Release Adapters/Store/Eventualize.Core.Adapters.RelationalStore.Common/Eventualize.Core.Adapters.RelationalStore.Common.csproj -o .
          dotnet pack  --no-build -c Release Adapters/Store/Eventualize.Core.Adapters.RelationalStore.Adapters/Eventualize.Core.Adapters.RelationalStore.Adapters.csproj -o .
          dotnet nuget push *.nupkg -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_API_KEY}} --skip-duplicate -n
        shell: bash
        